### ISSUE TITLE
Bring in the improvements branch

### ISSUE THREAD

**Issue by Falco20019** [Chatham/LetsTrace.Jaeger#1]
Analogous to https://github.com/Chatham/LetsTrace/issues/5.

Improvement branch can be find at [Falco20019/LetsTrace.Jaeger:improvements](https://github.com/Falco20019/LetsTrace.Jaeger/tree/improvements/src). It would be nice to get this merged in an incorporated soon. I'm creating this so we can track what all needs to be done before we merge.

Know to be missing:
- [x] Needs LetsTrace changes to be merged and published on NuGet to fulfill dependency
- [ ] Waiting for official NuGET package of THRIFT (see https://issues.apache.org/jira/browse/THRIFT-4512)
- [x] Update of unit tests

**Comment by grounded042** [comment]
As I mentioned in Chatham/LetsTrace#5, we could potentially publish the Thrift package ourself, but I'm not a big fan of that. The one reason I've been thinking about that is because it might help down the road when they actually officially publish a package - if we've been pulling in a dep all along, switching it might not be that big of a deal...but IMO that's not a good enough reason to pull the package out and publish it ourselves.

**Comment by Falco20019** [comment]
I think sticking with `ILRepack` looks like our best option for now until there is an official package.

**Comment by mweinand** [comment]
The `Jaeger.Thrift` library here is based on https://github.com/jaegertracing/jaeger-idl correct?  Supposing there is a Thrift NuGet package that is created (whether official or not), would you then package `Jaeger.Thrift` as a separate package as well to avoid needing `ILRepack`?

I'm wondering if it would make sense to make the `Jaeger.Thrift` package right away and do the `ILRepack` in that project.  Then that project can have the external dependencies and `LetsTrace.Jaeger` can remain "clean."  If an official or unofficial Thrift package comes along, that `Jaeger.Thrift` project can handle all the updates and `LetsTrace.Jaeger` just updates its PackageReference.

**Comment by Falco20019** [comment]
Yes, it's built from `jaeger-idl`. I like the idea of moving this problem into another package. Java also has an own jar for jaeger-thrift with https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-thrift.

**Comment by yurishkuro** [comment]
+1, it's best if the core client is separated from thrift-based sender, since in the future we will most likely want to support protobuf as an alternative

**Comment by mweinand** [comment]
Do we want that in its own repository or should we keep it in this one (similar to how jaeger-client-java is structured)?  I'm thinking we'll want to be able to regenerate from jaeger-idl at build time so the build will probably need to be able to download the thrift compiler or have a build runner with it included.

**Comment by yurishkuro** [comment]
In other Jaeger clients we keep it in the same repository, but as a separate module when possible.

We pull IDL through the use of `git submodule`. As for generated classes, my preference is for this to be a manual step and have them checked in, because it makes life much easier for the other contributors who generally do not need to touch those and therefore do not need to worry about the additional infra like having `thriftc` binary installed (although we never use it directly, instead we use a docker image).

**Comment by grounded042** [comment]
Good call on this stuff - I think it would could have a Jaeger.Thrift nuget package with all of that in there. If it's in a separate package then I think we should also put it in a separate repo - I'd like to be able to be explicit in what version the Jaeger client is using so if / when there are any breaking changes we can make those changes without it breaking on build.

**Comment by grounded042** [comment]
If we're all good on breaking it out I can add an issue to make it a repo and set stuff up for that - though I think the repo should be owned by the jaegertracing org.

**Comment by mweinand** [comment]
Agreed on making it easy for other contributors to not have to regenerate it, but it would be good to have it scripted somewhere and follow the `git submodule` pattern the other clients are using so that if you do need to regenerate it, it isn't painful in its own right.  If it is in a separate repository and package, contributors to `LetsTrace.Jaeger` shouldn't need to be exposed to it unless there is a Jaeger update that would require `thriftc` anyway.

**Comment by Falco20019** [comment]
I'm fine with having it in a separate repository for versioning, including the jaeger-idl repo using submodule.

**Comment by grounded042** [comment]
Yup @mweinand, we'll make sure the regeneration is scripted out so that we don't have to figure it out each time.

**Comment by grounded042** [comment]
I created an issue for this in #2. We can chat more about breaking that over there if anyone has more to add.

**Comment by yurishkuro** [comment]
> but it would be good to have it scripted somewhere 

Yes, absolutely. In Go client we have `make thrift` target.

> I'm fine with having it in a separate repository for versioning, including the jaeger-idl repo using submodule.

Why a separate repository? Can't a single C# repo contain multiple modules, like jaeger-client-java?

**Comment by grounded042** [comment]
@yurishkuro we certainly could put them in the same repo - I've seen different people do things different ways for C#. In the current workflow we have setup for the publishing of the NuGet we would always publish a NuGet package for LetsTrace.Jaeger and Jaeger.Thrift even if only one of them had changes. This is more of a build system limitation and I'll look into alternate systems besides Appveyor.

**Comment by yurishkuro** [comment]
I think it's perfectly fine, we have >5 modules in the Java client repo and they are all versioned at the same time. Having everything in one repo makes it much easier to develop (a mini mono-repo).

**Comment by Falco20019** [comment]
This was merged as part of https://github.com/Chatham/LetsTrace/issues/9
